x-pg-creds: &pg-creds
  POSTGRES_USER: teleport-db-admin
  POSTGRES_PASSWORD: supersecurepassword
  POSTGRES_DB: vehicleInventory
  POSTGRES_HOST: postgres:5432
  DATABASE_URI: postgresql+psycopg2://teleport-db-admin:supersecurepassword@postgres:5432/vehicleInventory

services:
  # Postgres 17 Database
  postgres:
    image: postgres:17
    container_name: apex_postgres
    restart: always
    environment:
      <<: *pg-creds
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  # The Main FastAPI App
  apex-auto-api:
    build:
      context: .
      dockerfile: api_server/Dockerfile
    container_name: apex-auto-api-server
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    environment:
      <<: *pg-creds
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/api_server

  # The MCP Server
  apex-auto-mcp:
    build:
      context: .
      dockerfile: mcp_server/Dockerfile
    container_name: apex-auto-mcp-server
    depends_on:
      - apex-auto-api
    ports:
      - "8100:8100"
    environment:
      API_URI: http://apex-auto-api:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/mcp_server

volumes:
  postgres_data:
