name: Build and Push Docker Images to GHCR

on:
  push:
    branches:
      #- main
      - feature/ci-cd
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  REPOSITORY: ${{ github.repository }}
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}
          tags: |
            type=sha,format=short

      - name: Build and push the API Server image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          file: api_server/Dockerfile
          platforms: ${{ env.PLATFORMS }}
          tags: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}-api-server:latest
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push the MCP Server image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          file: mcp_server/Dockerfile
          platforms: ${{ env.PLATFORMS }}
          tags: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}-mcp-server:latest
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  delete-old-tags:
    runs-on: ubuntu-latest
    needs: build-and-push
    permissions:
      contents: read
      packages: write # Needed for deletion

    steps:
      - name: Delete old image API Server versions
        uses: snok/container-retention-policy@v3.0.0
        with:
          account: user
          image-names: ${{ env.REPOSITORY }}-api-server
          cut-off: 20m
          keep-n-most-recent: 2
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete old MCP Server image versions
        uses: snok/container-retention-policy@v3.0.0
        with:
          account: user
          image-names: ${{ env.REPOSITORY }}-mcp-server
          cut-off: 20m
          keep-n-most-recent: 2
          token: ${{ secrets.GITHUB_TOKEN }}